# Default deny ingress and egress for task pods
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all
  namespace: {{ .Values.tasks.namespace }}
spec:
  policyTypes:
    - Ingress
    - Egress
---
# Allow egress traffic to the public Internet from task pods
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-internet-only
  namespace: {{ .Values.tasks.namespace }}
spec:
  policyTypes:
  - Egress
  egress:
  # Allow DNS to kube-dns
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  # Allow TCP to the orchestrator
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/component: orchestrator
    ports:
      - port: {{ .Values.orchestrator.service.port }}
        protocol: TCP
  # Allow public Internet traffic
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
