# The Planetary database persistent volume claim
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planetary-database-pvc
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.storage.storageClass }}
  storageClassName: {{ .Values.postgresql.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
{{- end }}
