{{- if .Values.serviceAccount.create -}}
# Role for cluster access for the orchestrator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ default "planetary-tasks" .Values.tasksNamespace }}
  name: orchestrator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete"]
---
# Service account for the orchestrator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . | default "orchestrator-service-account" }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
# Role binding for the orchestrator
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-role-binding
  namespace: {{ .Values.tasksNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrator-role
subjects:
- kind: ServiceAccount
  name: {{ include "chart.serviceAccountName" . | default "planetary-service-account" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
