# The Planetary API service
apiVersion: v1
kind: Service
metadata:
  name: planetary-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
# The Planetary orchestrator service
apiVersion: v1
kind: Service
metadata:
  name: planetary-orchestrator
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orchestrator.service.type }}
  ports:
    - port: {{ .Values.orchestrator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
