# This file is used to install the Planetary chart into a "development" cluster.
# See README.md for a walkthrough on installing the chart.
api:
  replicas: 1
  allowAuthorizationFallback: true
  log: info
  image:
    name: stjude-rust-labs/planetary-api
    tag: dev

orchestrator:
  replicas: 1
  log: info
  image:
    name: stjude-rust-labs/planetary-orchestrator
    tag: dev
  storage:
    nfs:
      server: 10.96.85.10
      path: /orchestrator

monitor:
  log: info
  image:
    name: stjude-rust-labs/planetary-monitor
    tag: dev

transporter:
  log: info
  image:
    name: stjude-rust-labs/planetary-transporter
    tag: dev

migration:
  image:
    name: stjude-rust-labs/planetary-migration
    tag: dev

postgresql:
  enabled: true
  resources:
    limits:
      memory: '8Gi'

# Enable support for "local" (file://) URLs using NFS-backed storage. 
# This will segment the local storage by user name so that task pods
# can only access the files for the user related to the task.
local:
  storage:
    nfs:
      server: 10.96.85.10
      path: /local/{{ `{{ username }}` }}

extra:
# Create an NFS service for the shared storage
- apiVersion: nfs.krestomat.io/v1alpha1
  kind: Ganesha
  metadata:
    name: planetary-nfs
    namespace: planetary
  spec:
    # Use 1000 as that's the uid/gid used by Planetary containers
    ganeshaExportUserid: 1000
    ganeshaExportGroupid: 1000
    ganeshaExportMode: '0700'
    ganeshaPvcDataSize: 1Gi
    # Do not generate a storage class
    ganeshaGeneratedNfsScNeeded: false
    # A static cluster IP is required for the service as nodes mount the NFS volume without access to `kube-dns`
    ganeshaServiceClusterIp: 10.96.85.10
# A job responsible for creating the expected directories for the orchestrator and local shares
# Without this, the monitor and orchestrator pods won't start 
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: create-nfs-dirs
    namespace: planetary
  spec:
    activeDeadlineSeconds: 60
    ttlSecondsAfterFinished: 60
    backoffLimit: 1
    template:
      spec:
        securityContext:
          fsGroup: 1000
        containers:
        - name: create-dirs
          securityContext:
            runAsUser: 1000
          image: alpine:latest
          command: ["mkdir",  "-p", "/mnt/nfs/local", "/mnt/nfs/orchestrator"]
          volumeMounts:
          - name: nfs
            mountPath: /mnt/nfs
        restartPolicy: Never
        volumes:
        - name: nfs
          nfs:
            server: 10.96.85.10
            path: /
